model: "InternVL3-2B"
model_space: "OpenGVLab"
cache_dir: ".cache/"
dataset_path: "/mnt/datasets/ucf_crime"
meta_path: "/home/kirill/DeviantBehaviorResearch/Anomaly_Test.txt"
output_prefix: "basic_prompt_lora"
fps: 0.5
num_frames: 16
max_new_tokens: 16
prompt: "/home/kirill/DeviantBehaviorResearch/prompts/basic.txt"
continue_from: null          # use an int index or leave null
