model: "Qwen2.5-VL-7B-Instruct"
model_space: "Qwen"
cache_dir: ".cache/"
dataset_path: "/mnt/datasets/ucf_crime"
meta_path: "/home/kirill/DeviantBehaviorResearch/Anomaly_Test.txt"
output_prefix: "basic_prompt"
fps: 0.5
num_frames: 16
max_new_tokens: 16
prompt: "/home/kirill/DeviantBehaviorResearch/prompts/zero_shot.txt"
continue_from: null          # use an int index or leave null
