model: "qwen2.5-vl-3b-instruct-trl-sft-ChartQA-2025-07-24-11-58-23/checkpoint-546" #"Qwen2.5-VL-7B-Instruct"
model_space: "" #"Qwen"
cache_dir: ".cache/"
dataset_path: "/mnt/datasets/ucf_crime"
meta_path: "/app/DeviantBehaviorResearch/Anomaly_Test.txt"
output_prefix: "cot"
fps: 0.5
num_frames: 16
max_new_tokens: 320
prompt: "/app/DeviantBehaviorResearch/prompts/cot.txt"
continue_from: null          # use an int index or leave null
